version: "3.9"

services:
  app:
    container_name: cozey-app
    image: node:18.18-alpine
    volumes:
      - ./app:/app
      - ./shared:/shared
    command: /bin/sh -c "cd app && npm install && npm run dev"
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}

  server:
    container_name: cozey-server
    image: node:18.18-alpine
    volumes:
      - ./server:/server
      - ./shared:/shared
    command: /bin/sh -c "cd server && npm install && npm run dev"
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
